modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="witchercraft"
version="1.0.0"
displayName="WitcherCraft"
displayURL="https://redboltmedia.net"
credits="hm"
authors="Ciochu, RedBoltMedia"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.witchercraft]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.witchercraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration